# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/suomi',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/suomi',
                'lib_path': 'suomi'},
  'syms': {'suomi.core': {'suomi.core.foo': ('core.html#foo', 'suomi/core.py')}}}
