"""Command-line interface for suomi workflows"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_cli.ipynb.

# %% auto #0
__all__ = ['suomi_create', 'suomi_latest']

# %% ../nbs/05_cli.ipynb #6770b6a7
from fastcore.script import call_parse
from .workflow import register_txt, register_latest

# %% ../nbs/05_cli.ipynb #b87f1fb2
@call_parse
def suomi_create(
    input_file: str,  # Input text file (one Finnish phrase per line)
    output_dir: str = "output",  # Output directory for TSV and audio
    overwrite: bool = False,  # Overwrite existing TSV
):
    "Create Anki flashcards from a Finnish text file"
    register_txt(input_file, output_dir, overwrite)

# %% ../nbs/05_cli.ipynb #097bcccb
@call_parse
def suomi_latest(
    input_dir: str = "texts",  # Directory with text files
    output_dir: str = "output",  # Output directory
    overwrite: bool = False,  # Overwrite existing
):
    "Process the most recently modified text file"
    register_latest(input_dir, output_dir, overwrite)
