"""Core utilities for file discovery and generic operations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['find_files_recursive', 'ffr', 'cattxt']

# %% ../nbs/00_core.ipynb 2
import re
from pathlib import Path

# %% ../nbs/00_core.ipynb 3
def _find_files_recursive(
    dirs: list[str] | list[Path], # List of directories to search recursively
    exts: list[str],                # List of file extensions (e.g., [".jpg", ".png", ".mp3"])
    prefix: str = ""                      # File name prefix to match (optional, empty string matches all)
) -> list[str]:                          # List of file paths matching the criteria
    """Recursively search directories for files with specified extensions and prefix.
    
    Searches each directory in search_dirs recursively and returns all files
    that match the given extensions and prefix.
    
    Examples:
        >>> _find_files_recursive(["images"], [".jpg", ".png"])
        ['images/05_Keho.jpg', 'images/05_Kasvot.jpg', ...]
        
        >>> _find_files_recursive(["images", "audio"], [".jpg", ".mp3"], prefix="05_")
        ['images/05_Keho.jpg', 'audio/05_Keho_00.mp3', ...]
    """
    # Compile regex pattern for extensions (case-insensitive)
    ext_pattern = "|".join(re.escape(ext) for ext in exts)
    pattern = re.compile(f"^{re.escape(prefix)}.*({ext_pattern})$", re.IGNORECASE)
    
    found = []    
    for d in dirs:
        cur = Path(d)
        if not cur.exists(): continue
        for f in cur.rglob('*'):
            if not f.is_file(): continue
            if pattern.search(f.name):
                found.append(str(f))
    
    return sorted(found)

# %% ../nbs/00_core.ipynb 4
def find_files_recursive(
    dirs: list[str] | list[Path], # List of directories to search recursively
    exts: list[str],               # List of file extensions (e.g., [".jpg", ".png", ".mp3"])
    prefix: str = ""               # File name prefix to match (optional, empty string matches all)
) -> list[str]:                    # List of file paths matching the criteria
    """Recursively search directories for files with specified extensions and prefix.

    Searches each directory recursively and returns all files matching the given
    extensions and prefix. This is the full function name; use `ffr` for a shorter alias.

    Examples:
        >>> find_files_recursive(["images"], [".jpg", ".png"])
        ['images/05_Keho.jpg', 'images/05_Kasvot.jpg', ...]

        >>> find_files_recursive(["images", "audio"], [".jpg", ".mp3"], prefix="05_")
        ['images/05_Keho.jpg', 'audio/05_Keho_00.mp3', ...]
    """
    return _find_files_recursive(dirs, exts, prefix)

#| export
def ffr(
    dirs: list[str] | list[Path], # List of directories to search recursively
    exts: list[str],               # List of file extensions (e.g., [".jpg", ".png", ".mp3"])
    prefix: str = ""               # File name prefix to match (optional, empty string matches all)
) -> list[str]:                    # List of file paths matching the criteria
    """Short alias for find_files_recursive.

    Convenient shorthand for find_files_recursive(). See that function for full documentation.

    Examples:
        >>> ffr(["images"], [".jpg", ".png"])
        ['images/05_Keho.jpg', 'images/05_Kasvot.jpg', ...]
    """
    return find_files_recursive(dirs, exts, prefix)

# %% ../nbs/00_core.ipynb 7
def cattxt(fn: str) -> list[str]:
    """Read text file and return list of lines (without newlines)."""
    with open(fn, encoding="utf-8") as f:
        return f.read().splitlines()

#cattxt("lääkarissä_kasvot.txt")[:4]
