# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_mp3.ipynb.

# %% auto #0
__all__ = ['piper_model', 'text2wav', 'wav2mp3', 'text2mp3', 'mp3s']

# %% ../nbs/02_mp3.ipynb #2c9e7c97-e31b-420e-bf1f-6a953f47310e
import csv
import os
import tempfile
from pathlib import Path
from subprocess import run, CalledProcessError
from urllib.request import urlretrieve

# %% ../nbs/02_mp3.ipynb #8sc061788i6
_MODEL_URL = "https://huggingface.co/rhasspy/piper-voices/resolve/main/fi/fi_FI/harri/medium"
_MODEL_NAME = "fi_FI-harri-medium.onnx"

def piper_model(cache_dir: Path | None = None) -> str:
    """Return path to Piper TTS model, downloading if needed.
    
    Model is cached in ~/.cache/suomi/models/.
    Downloads from HuggingFace on first use.
    """
    if cache_dir is None:
        cache_dir = Path.home() / ".cache" / "suomi"
    model_path = cache_dir / "models" / _MODEL_NAME
    if not model_path.exists():
        model_path.parent.mkdir(parents=True, exist_ok=True)
        print(f"Downloading {_MODEL_NAME}...")
        urlretrieve(f"{_MODEL_URL}/{_MODEL_NAME}", model_path)
        urlretrieve(f"{_MODEL_URL}/{_MODEL_NAME}.json", f"{model_path}.json")
        print(f"Saved to {model_path}")
    return str(model_path)

# %% ../nbs/02_mp3.ipynb #35fd79fa-e0e1-4f78-9c89-29c220ec1e1d
def text2wav(
    s: str = "pää on kipeä.",  # Text to convert to WAV
    wav: str = "output.wav",   # Output WAV file path
    model: str | None = None   # Piper TTS model path (auto-downloaded if None)
) -> None:
    """Convert text to WAV using Piper TTS."""
    if not s or not s.strip():
        return
    if model is None:
        model = piper_model()
    try:
        run(["piper", "--model", model, "--output_file", wav], input=s.encode(), check=True)
    except FileNotFoundError:
        raise RuntimeError(
            "Piper TTS not found. Install: pip install piper-tts\n"
            "Or download from: https://github.com/rhasspy/piper"
        )
    except CalledProcessError as e:
        raise RuntimeError(
            f"Piper TTS failed with exit code {e.returncode}\n"
            f"Check that model file exists: {model}\n"
            f"Error: {e}"
        )

def wav2mp3(
    wav: str = "output.wav",  # Input WAV file path
    mp3: str = "output.mp3"   # Output MP3 file path
) -> None:
    """Convert WAV to MP3 using ffmpeg."""
    try:
        run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", wav, "-codec:a", "libmp3lame", "-q:a", "4", mp3], check=True)
    except FileNotFoundError:
        raise RuntimeError(
            "ffmpeg not found. Install:\n"
            "  Ubuntu/Debian: sudo apt install ffmpeg\n"
            "  macOS: brew install ffmpeg\n"
            "  Windows: Download from https://ffmpeg.org/"
        )
    except CalledProcessError as e:
        raise RuntimeError(
            f"ffmpeg conversion failed with exit code {e.returncode}\n"
            f"Input: {wav}, Output: {mp3}"
        )

def text2mp3(
    s: str = "pää on kipeä.",  # Text to convert to MP3
    mp3: str = "output.mp3",   # Output MP3 file path
    model: str | None = None   # Piper TTS model path (auto-downloaded if None)
) -> None:
    """Convert text to MP3 via WAV using Piper TTS and ffmpeg."""
    if not s or not s.strip():
        return
    if model is None:
        model = piper_model()
    fd, wav = tempfile.mkstemp(suffix=".wav")
    os.close(fd)
    try:
        text2wav(s, wav=wav, model=model)
        wav2mp3(wav=wav, mp3=mp3)
    finally:
        if os.path.exists(wav):
            os.remove(wav)

_MAX_ROWS = 100  # 2-digit zero-padding supports indices 0-99

def mp3s(
    tsv: str,                  # Path to TSV file
    output_dir: str = "audio", # Output directory for MP3 files
    model: str | None = None   # Piper TTS model path (auto-downloaded if None)
) -> None:
    """Generate MP3 files for all Finnish entries in TSV file.
    
    Supports up to 100 rows (indices 00-99) due to 2-digit zero-padding.
    """
    if model is None:
        model = piper_model()
    assert Path(tsv).is_file(), f"TSV file not found: {tsv}"
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    with open(tsv, encoding="utf-8") as f:
        rows = list(csv.DictReader(f, delimiter="\t"))
    if len(rows) >= _MAX_ROWS:
        raise ValueError(
            f"TSV has {len(rows)} rows but mp3s() supports up to {_MAX_ROWS} "
            f"(2-digit zero-padding 00-99). Split the TSV into smaller files."
        )
    for i, row in enumerate(rows):
        if "Finnish" not in row:
            continue
        finnish_text = row["Finnish"].strip()
        if not finnish_text:
            continue
        text2mp3(s=finnish_text, mp3=f"{output_dir}/{Path(tsv).stem}_{i:02}.mp3", model=model)
