# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_mp3.ipynb.

# %% auto 0
__all__ = ['text2wav', 'wav2mp3', 'text2mp3', 'mp3s']

# %% ../nbs/02_mp3.ipynb 2
import csv
import os
from pathlib import Path
from subprocess import run, CalledProcessError
import shlex

# %% ../nbs/02_mp3.ipynb 3
def text2wav(
    s: str = "pää on kipeä.",  # Text to convert to WAV
    wav: str = "output.wav",   # Output WAV file path
    model: str = 'models/fi_FI-harri-low.onnx'  # Piper TTS model path
) -> None:
    """Convert text to WAV using Piper TTS."""
    try:
        run(shlex.split(f"piper --model {model} --output_file {wav}"), input=s.encode(), check=True)
    except FileNotFoundError:
        raise RuntimeError(
            "Piper TTS not found. Install: pip install piper-tts\n"
            "Or download from: https://github.com/rhasspy/piper"
        )
    except CalledProcessError as e:
        raise RuntimeError(
            f"Piper TTS failed with exit code {e.returncode}\n"
            f"Check that model file exists: {model}\n"
            f"Error: {e}"
        )

def wav2mp3(
    wav: str = "output.wav",  # Input WAV file path
    mp3: str = "output.mp3"   # Output MP3 file path
) -> None:
    """Convert WAV to MP3 using ffmpeg."""
    try:
        run(shlex.split(f"ffmpeg -hide_banner -loglevel error -y -i {wav} -codec:a libmp3lame -q:a 4 {mp3}"), check=True)
    except FileNotFoundError:
        raise RuntimeError(
            "ffmpeg not found. Install:\n"
            "  Ubuntu/Debian: sudo apt install ffmpeg\n"
            "  macOS: brew install ffmpeg\n"
            "  Windows: Download from https://ffmpeg.org/"
        )
    except CalledProcessError as e:
        raise RuntimeError(
            f"ffmpeg conversion failed with exit code {e.returncode}\n"
            f"Input: {wav}, Output: {mp3}"
        )

def text2mp3(
    s: str = "pää on kipeä.",  # Text to convert to MP3
    mp3: str = "output.mp3",   # Output MP3 file path
    model: str = 'models/fi_FI-harri-low.onnx'  # Piper TTS model path
) -> None:
    """Convert text to MP3 via WAV using Piper TTS and ffmpeg."""
    wav = "output.wav"
    try:
        text2wav(s, wav=wav, model=model)
        wav2mp3(wav=wav, mp3=mp3)
    finally:
        # Clean up temporary WAV file
        if os.path.exists(wav):
            os.remove(wav)

def mp3s(
    tsv: str,                  # Path to TSV file
    output_dir: str = "audio", # Output directory for MP3 files
    model: str = 'models/fi_FI-harri-low.onnx'  # Piper TTS model path
) -> None:
    """Generate MP3 files for all Finnish entries in TSV file."""
    assert Path(tsv).is_file(), f"TSV file not found: {tsv}"
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    with open(tsv, encoding="utf-8") as f:
        for i, row in enumerate(csv.DictReader(f, delimiter="\t")):
            if "Finnish" not in row:
                continue
            finnish_text = row["Finnish"].strip()
            if not finnish_text:
                continue
            text2mp3(s=finnish_text, mp3=f"{output_dir}/{Path(tsv).stem}_{i:02}.mp3", model=model)
