"""TSV file generation and manipulation functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tsv.ipynb.

# %% auto #0
__all__ = ['texts2tsv', 'tsv_load', 'cattsv', 'tsv_dump', 'dump_tsv', 'update_tsv_media_paths', 'tsv_finnish', 'tsv_status',
           'tsv_xlate', 'tsv_en_ja', 'tsv_mp3', 'tsv_img', 'tsv_complete']

# %% ../nbs/01_tsv.ipynb #3
import os
import csv
import re
import hashlib
import warnings
from pathlib import Path
from .core import ffr
from .xlate import xtexts

# %% ../nbs/01_tsv.ipynb #11
def texts2tsv(
    texts: list[str],  # List of Finnish texts to translate
    output_path: str,  # Output TSV file path (e.g., "tsvs/06_Ruoka.tsv")
    tags: str | list[str] = "lang::fi"  # Tags (string or list), lang::fi auto-included
) -> None:
    """
    Main function: translate Finnish words and create TSV file.
    Example:
        >>> texts = ["omena", "banaani", "Minä syön omenaa"]
        >>> texts2tsv(texts, "tsvs/06_Ruoka.tsv", tags="src::daily")
        >>> texts2tsv(texts, "tsvs/06_Ruoka.tsv", tags=["src::class", "level::A1"])
    """
    # Process tags
    if isinstance(tags, str):
        tag_list = [t.strip() for t in tags.split(",")]
    else:
        tag_list = list(tags)
    
    # Always ensure lang::fi is included
    if "lang::fi" not in tag_list:
        tag_list.insert(0, "lang::fi")
    
    # Convert to comma-separated string for TSV
    tag_string = ",".join(tag_list)
    
    xsls = xtexts(texts)
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)   
    with open(out, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["Finnish", "English", "Japanese", "mp3_path", "img_path", "tags"],
            delimiter="\t"
        )
        writer.writeheader()
        for x in xsls:
            x["tags"] = tag_string  # Add tags to each row
            writer.writerow(x)

# %% ../nbs/01_tsv.ipynb #12b12179-cd94-4f2a-96da-09d75e5693b8
def tsv_load(
    fname: str,  # Path to TSV file
    skip_empty: bool = False  # Skip empty rows
) -> tuple[list[dict], list[str]]:
    """Read TSV file and return (rows, fieldnames) tuple.
    
    Caller can unpack as needed:
        rows, fields = tsv_load(fname)
        rows = tsv_load(fname)[0]  # Just rows
    """
    rows = []   
    with open(fname, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        fields = list(reader.fieldnames) if reader.fieldnames else []
        
        for row in reader:
            if skip_empty and not any(row.values()):
                continue
            rows.append(row)
    
    return rows, fields

#| export
def cattsv(fname: str, skip_empty: bool = False) -> tuple[list[dict], list[str]]:
    """Deprecated: Use tsv_load() instead."""
    warnings.warn("cattsv() is deprecated. Use tsv_load() instead.", DeprecationWarning, stacklevel=2)
    return tsv_load(fname, skip_empty)

# %% ../nbs/01_tsv.ipynb #aoljt3nqkq5
def tsv_dump(
    fname: str,  # Path to TSV file
    rows: list[dict],  # List of row dictionaries
    fieldnames: list[str] | None = None  # Column names (if None, use REQUIRED_COLUMNS)
) -> None:
    """Write rows to TSV file.
    
    If fieldnames not provided, uses standard columns:
    ["Finnish", "English", "Japanese", "mp3_path", "finnish_hash", "img_path", "tags"]
    """
    if fieldnames is None:
        fieldnames = ["Finnish", "English", "Japanese", "mp3_path", "finnish_hash", "img_path", "tags"]
    
    with open(fname, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)

#| export
def dump_tsv(fname: str, rows: list[dict], fieldnames: list[str] | None = None) -> None:
    """Deprecated: Use tsv_dump() instead."""
    warnings.warn("dump_tsv() is deprecated. Use tsv_dump() instead.", DeprecationWarning, stacklevel=2)
    tsv_dump(fname, rows, fieldnames)

# %% ../nbs/01_tsv.ipynb #l5he3tyi6o
def _assign_files_by_row(
    all_files: list[str],  # All files found matching stem prefix
    stem: str,             # File stem (TSV filename without extension)
    extensions: list[str], # List of extensions to process (e.g., [".mp3"] or [".png", ".jpg"])
    num_rows: int,         # Number of rows in TSV (determines result list length)
) -> list[str]:            # List of file paths, one per row (empty string if not found)
    """Assign files to rows based on naming conventions.
    
    File naming rules:
    - Row-specific: {stem}_NN.ext (e.g., "06_Daily_00.mp3" for row 0)
    - Common: {stem}.ext (e.g., "06_Daily.png" for all rows)
    
    Behavior:
    - First tries row-specific files ({stem}_NN.ext)
    - If row-specific not found and common file ({stem}.ext) exists, uses common file
    - If neither found, returns empty string
    
    For multiple extensions (e.g., [".png", ".jpg"]), uses first found in order.
    
    Returns a list of length num_rows where index i corresponds to row i.
    """
    import re
    
    # Build extension pattern
    ext_pat = '|'.join(re.escape(ext.lstrip('.')) for ext in extensions)
    row_pat = re.compile(rf"^{re.escape(stem)}_(\d+)\.({ext_pat})$", re.IGNORECASE)
    common_pat = re.compile(rf"^{re.escape(stem)}\.({ext_pat})$", re.IGNORECASE)
    
    # Classify files
    by_row = {}  # {row_idx: {ext: path}}
    common = {}  # {ext: path}
    
    for path in all_files:
        name = Path(path).name
        m = row_pat.match(name)
        if m:
            idx, ext = int(m.group(1)), "." + m.group(2).lower()
            by_row.setdefault(idx, {})[ext] = path
        else:
            # Check if it's a common file
            m = common_pat.match(name)
            if m:
                common["." + m.group(1).lower()] = path
    # Assign files to rows (respecting extension priority)
    # Use common files only if they exist (determined by whether common dict has entries)
    result = []
    for i in range(num_rows):
        path = ""
        # First try row-specific files
        if i in by_row:
            for ext in extensions:
                if ext in by_row[i]:
                    path = by_row[i][ext]
                    break
        # If not found and common files exist, try common files
        if not path and common:
            for ext in extensions:
                if ext in common:
                    path = common[ext]
                    break
        result.append(path)
    
    return result

# %% ../nbs/01_tsv.ipynb #2iz6ke386cr
def update_tsv_media_paths(
    tsv: str,               # Path to TSV file
    dirs: list[str] = ["audio", "images"], # Directories to search for media files
) -> None:
    """Update TSV file with mp3 and image paths based on file name conventions.
    
    Searches for media files matching the TSV filename stem and assigns them to rows.
    Only non-empty rows are counted as entries (empty rows are skipped).
    
    File naming rules (where {stem} = TSV filename without extension, NN = zero-padded row index):
    
    MP3 files (row-specific only):
    - Pattern: {stem}_NN.mp3 (e.g., "05_Keho_00.mp3" for row 0)
    - Priority: {stem}_NN.mp3 → "" (common files not used for MP3)
    - Searches in: dirs (recursively)
    
    Image files (row-specific + common fallback):
    - Row-specific: {stem}_NN.{png,jpg} (e.g., "05_Keho_00.png" for row 0)
       - If exists, use this (common files are ignored)
    - Common: {stem}.{png,jpg} (e.g., "05_Keho.png" for all rows)
       - Only used if row-specific file not found
    - Priority: {stem}_NN.png > {stem}_NN.jpg > {stem}.png > {stem}.jpg > ""
    - Searches in: dirs (recursively)
    
    Examples:
        >>> update_tsv_media_paths("tsvs/05_Keho.tsv")
        # For row 0:
        # - MP3: "05_Keho_00.mp3" if exists, else ""
        # - Image: "05_Keho_00.png" if exists, else "05_Keho_00.jpg" if exists,
        #          else "05_Keho.png" if exists, else "05_Keho.jpg" if exists, else ""
    """
    tsv_path = Path(tsv)
    stem = tsv_path.stem
    all_files = ffr(dirs, [".mp3", ".png", ".jpg"], prefix=stem)
    
    # Read TSV to get rows, fieldnames, and entry count (skipping empty rows)
    rows, fields = tsv_load(tsv, skip_empty=True)
    num_entries = len(rows)
    
    # Assign files using common helper function (based on actual entry count)
    # MP3: row-specific only (common files won't match .mp3 pattern in practice)
    mp3_files = _assign_files_by_row(all_files, stem, [".mp3"], num_entries)
    
    # Images: row-specific + common fallback, png > jpg priority
    img_files = _assign_files_by_row(all_files, stem, [".png", ".jpg"], num_entries)

    if num_entries > 100:
        warnings.warn(
            f"TSV '{tsv}' has {num_entries} entries; ensure mp3/image files exist for indexes >= 100.",
            stacklevel=2,
        )

    # Update rows with file paths (using enumerate to match entry indices)
    for i, row in enumerate(rows):
        row['mp3_path'] = mp3_files[i]
        row['img_path'] = img_files[i]
    
    # Write updated TSV using tsv_dump
    tsv_dump(tsv, rows, fields)

# %% ../nbs/01_tsv.ipynb #8saobr76p2t
def calculate_finnish_hash(finnish: str) -> str:
    """Calculate deterministic hash for Finnish text (for duplicate detection).

    Normalization rules:
    - Lowercase
    - Strip leading/trailing whitespace
    - Collapse multiple spaces to single space

    Returns: First 8 characters of SHA256 hash (e.g., "a3f2b1c9")

    Examples:
        >>> calculate_finnish_hash("Hei")
        'a1b2c3d4'  # Consistent hash
        >>> calculate_finnish_hash("hei")
        'a1b2c3d4'  # Same hash (case normalized)
        >>> calculate_finnish_hash("  Hei  maailma  ")
        'e5f6g7h8'  # Whitespace normalized
    """
    # Normalize: lowercase, strip whitespace, collapse multiple spaces
    normalized = re.sub(r'\s+', ' ', finnish.strip().lower())
    
    # Calculate SHA256 hash
    hash_bytes = hashlib.sha256(normalized.encode('utf-8')).hexdigest()
    
    # Return first 8 characters
    return hash_bytes[:8]

# %% ../nbs/01_tsv.ipynb #15898b95-f210-4dcd-9569-1ae4e783c8ad
def ensure_columns(tsv: str) -> None:
    """Ensure TSV has all required columns, add missing ones.

    Migration helper for old TSV files. Adds missing columns with empty values.
    
    Special handling for finnish_hash:
    - If column missing or value empty, auto-calculates from Finnish column
    - Preserves existing finnish_hash values (does not overwrite)
    """
    REQUIRED_COLUMNS = ["Finnish", "English", "Japanese", "mp3_path", "finnish_hash", "img_path", "tags"]
    rows, fields = tsv_load(tsv)
    missing = [col for col in REQUIRED_COLUMNS if col not in fields]
    
    # Add missing columns with empty values
    if missing:
        for row in rows:
            for col in missing:
                row[col] = ""
    
    # Auto-calculate finnish_hash for rows where it's missing or empty
    for row in rows:
        if not row.get("finnish_hash", "").strip():
            finnish_text = row.get("Finnish", "")
            if finnish_text:
                row["finnish_hash"] = calculate_finnish_hash(finnish_text)

    tsv_dump(tsv, rows, REQUIRED_COLUMNS)

# %% ../nbs/01_tsv.ipynb #pyzxjb61ucq
def tsv_finnish(
    texts: list[str],
    output_path: str,
    tags: str | list[str] = "lang::fi",
    overwrite: bool = False,
) -> None:
    """Create TSV with Finnish column only. Other columns are empty.
    
    Automatically removes duplicates (case-insensitive, whitespace-normalized)
    and filters out empty/whitespace-only texts.
    Pre-computes finnish_hash for each entry.
    
    Args:
        texts: Finnish words/phrases to add
        output_path: TSV file path to create
        tags: Tags to add. Default "lang::fi". Use comma-separated string or list.
              Examples: "lang::fi,src::daily" or ["lang::fi", "src::daily"]
        overwrite: Overwrite existing TSV if True (default: False for safety)

    Examples:
        >>> tsv_finnish(["kissa", "koira"], "vocab.tsv")  # Uses default tags="lang::fi"
        >>> tsv_finnish(["kissa", "Kissa", "koira"], "vocab.tsv")  # Removes duplicate "Kissa"
        >>> tsv_finnish(["kissa"], "vocab.tsv", tags="lang::fi,src::daily")
        >>> tsv_finnish(["koira"], "vocab.tsv", tags=["src::class", "level::A1"])
    """
    out = Path(output_path)
    if out.exists() and not overwrite:
        raise FileExistsError(f"TSV file already exists: {output_path}. Use overwrite=True to replace.")
    out.parent.mkdir(parents=True, exist_ok=True)
    tag_string = ",".join([t.strip() for t in tags.split(",")] if isinstance(tags, str) else list(tags))
    
    # Remove duplicates and empty texts using hash-based deduplication
    seen_hashes = set()
    unique_texts = []
    for text in texts:
        if not text or not text.strip():
            continue
        text_hash = calculate_finnish_hash(text)
        if text_hash not in seen_hashes:
            seen_hashes.add(text_hash)
            unique_texts.append((text, text_hash))
    
    with open(out, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["Finnish", "English", "Japanese", "mp3_path", "finnish_hash", "img_path", "tags"],
            delimiter="\t"
        )
        writer.writeheader()
        for text, text_hash in unique_texts:
            writer.writerow({
                "Finnish": text,
                "English": "",
                "Japanese": "",
                "mp3_path": "",
                "finnish_hash": text_hash,
                "img_path": "",
                "tags": tag_string
            })

# %% ../nbs/01_tsv.ipynb #ril1xwmdbo
def tsv_status(tsv: str) -> dict:
    """Analyze TSV completion status (read-only, no file modification).

    Returns:
        {
            "total_rows": 10,
            "finnish_filled": 10,
            "english_missing": 2,
            "japanese_missing": 2,
            "mp3_missing": 3,
            "img_missing": 8,
            "fully_complete": 5,
            "completion_rate": 0.5
        }
    """
    rows, _ = tsv_load(tsv, skip_empty=True)

    status = {
        "total_rows": len(rows),
        "finnish_filled": 0,
        "english_missing": 0,
        "japanese_missing": 0,
        "mp3_missing": 0,
        "img_missing": 0,
        "fully_complete": 0
    }

    for row in rows:
        fi = row.get("Finnish", "").strip()
        en = row.get("English", "").strip()
        ja = row.get("Japanese", "").strip()
        mp3 = row.get("mp3_path", "").strip()
        img = row.get("img_path", "").strip()

        if fi:
            status["finnish_filled"] += 1
        if not en:
            status["english_missing"] += 1
        if not ja:
            status["japanese_missing"] += 1
        if not mp3:
            status["mp3_missing"] += 1
        if not img:
            status["img_missing"] += 1

        if all([fi, en, ja, mp3]):
            status["fully_complete"] += 1

    status["completion_rate"] = status["fully_complete"] / status["total_rows"] if status["total_rows"] > 0 else 0.0

    return status

# %% ../nbs/01_tsv.ipynb #gv9pdtahhmw
def tsv_xlate(
    tsv: str,
    target_langs: list[str] = ["English", "Japanese"],
    skip_filled: bool = True,
    batch_size: int = 10
) -> dict:
    """Translate empty fields in TSV using API.
    
    Processes only rows with empty English/Japanese columns.
    Uses batch processing to handle API rate limits.
    
    Args:
        tsv: TSV file path
        target_langs: Languages to translate (currently only ["English", "Japanese"])
        skip_filled: Skip rows that already have translations
        batch_size: Number of rows per API batch
        
    Returns:
        {
            "translated": 8,      # Successfully translated rows
            "skipped": 2,         # Already filled rows
            "errors": 1,          # Failed rows
            "error_details": [    # Error details list
                {"row": 3, "finnish": "text", "error": "API timeout"}
            ]
        }
    """
    ensure_columns(tsv)
    rows, fields = tsv_load(tsv)
    
    result = {"translated": 0, "skipped": 0, "errors": 0, "error_details": []}
    to_translate = []
    
    # Collect rows that need translation
    for i, row in enumerate(rows):
        if not row["Finnish"].strip():
            continue
        if skip_filled and row["English"].strip():
            result["skipped"] += 1
            continue
        to_translate.append((i, row))
    
    # Batch processing
    for batch_start in range(0, len(to_translate), batch_size):
        batch = to_translate[batch_start:batch_start + batch_size]
        finnish_texts = [row["Finnish"] for _, row in batch]
        
        try:
            translations = xtexts(finnish_texts)
            for (i, row), trans in zip(batch, translations):
                row["English"] = trans.get("English", "")
                row["Japanese"] = trans.get("Japanese", "")
                result["translated"] += 1
        except Exception as e:
            # Batch failed, retry one by one
            for i, row in batch:
                try:
                    trans = xtexts([row["Finnish"]])[0]
                    row["English"] = trans.get("English", "")
                    row["Japanese"] = trans.get("Japanese", "")
                    result["translated"] += 1
                except Exception as err:
                    result["errors"] += 1
                    result["error_details"].append({
                        "row": i,
                        "finnish": row["Finnish"],
                        "error": str(err)
                    })
    
    # Write back
    tsv_dump(tsv, rows, fields)
    
    return result

# %% ../nbs/01_tsv.ipynb #4rimscvm4d4
def tsv_en_ja(
    texts_dicts: list[dict],  # Translation dicts with Finnish, English, Japanese
    tsv: str                   # TSV file to update
) -> None:
    """Merge translations into TSV using hash matching.
    
    Updates English/Japanese columns for matching Finnish texts.
    Uses finnish_hash for matching (case-insensitive, whitespace-normalized).
    Preserves existing data (mp3_path, img_path, etc).
    
    Args:
        texts_dicts: List of dicts with keys: Finnish, English, Japanese
        tsv: Path to TSV file to update
        
    Examples:
        >>> tsv_finnish(["kissa"], "vocab.tsv")
        >>> tsv_en_ja([{"Finnish": "kissa", "English": "cat", "Japanese": "猫"}], "vocab.tsv")
    """
    # Build hash lookup: {hash: {English, Japanese}}
    translations = {}
    for d in texts_dicts:
        h = calculate_finnish_hash(d["Finnish"])
        translations[h] = {"English": d.get("English", ""), "Japanese": d.get("Japanese", "")}
    
    # Read TSV
    rows, fields = tsv_load(tsv)
    
    # Update rows with translations (match by hash)
    for row in rows:
        h = row.get("finnish_hash", "")
        if h in translations:
            # Only update if currently empty (preserve existing)
            if not row.get("English", "").strip():
                row["English"] = translations[h]["English"]
            if not row.get("Japanese", "").strip():
                row["Japanese"] = translations[h]["Japanese"]
    
    # Write back
    tsv_dump(tsv, rows, fields)

# %% ../nbs/01_tsv.ipynb #1pnpg17xy8ji
def tsv_mp3(
    tsv: str,                    # TSV file to update
    output_dir: str = "audio",   # Output directory for MP3 files
    model: str | None = None     # Piper model path (auto-downloaded if None)
) -> None:
    """Generate MP3 files and update TSV with paths (differential update).
    
    Only processes rows where mp3_path is empty and Finnish text is non-empty.
    Supports up to 100 rows (indices 00-99) due to 2-digit zero-padding.
    
    Examples:
        >>> tsv_finnish(["kissa"], "vocab.tsv")
        >>> tsv_mp3("vocab.tsv", output_dir="audio")
        # Creates: audio/vocab_00.mp3
    """
    from suomi.mp3 import text2mp3
    
    rows, fields = tsv_load(tsv)
    if len(rows) >= 100:
        raise ValueError(
            f"TSV has {len(rows)} rows but tsv_mp3() supports up to 100 "
            f"(2-digit zero-padding 00-99). Split the TSV into smaller files."
        )
    stem = Path(tsv).stem
    
    for i, row in enumerate(rows):
        finnish = row.get("Finnish", "").strip()
        if not finnish:
            continue
        if not row.get("mp3_path", "").strip():
            mp3_file = f"{output_dir}/{stem}_{i:02d}.mp3"
            text2mp3(finnish, mp3_file, model)
            row["mp3_path"] = mp3_file
    
    tsv_dump(tsv, rows, fields)

# %% ../nbs/01_tsv.ipynb #ij8apt3cxwh
def tsv_img(
    tsv: str,                           # TSV file to update
    dirs: list[str] = ["images"]        # Directories to search for images
) -> None:
    """Search for images and update TSV with paths.
    
    Searches for existing image files matching TSV filename.
    Updates only rows with empty img_path (differential update).
    Uses existing _assign_files_by_row() for file matching.
    
    File priority: row-specific .png > row-specific .jpg > common .png > common .jpg
    
    Args:
        tsv: TSV file path
        dirs: Directories to search for images
        
    Examples:
        >>> tsv_finnish(["kissa"], "vocab.tsv")
        >>> tsv_img("vocab.tsv", dirs=["images"])
    """
    rows, fields = tsv_load(tsv)
    stem = Path(tsv).stem
    
    # Find all image files
    all_imgs = ffr(dirs, [".png", ".jpg"], prefix=stem)
    
    # Assign images to rows using existing helper
    img_paths = _assign_files_by_row(all_imgs, stem, [".png", ".jpg"], len(rows))
    
    # Update only empty img_path
    for i, row in enumerate(rows):
        if not row.get("img_path", "").strip():
            row["img_path"] = img_paths[i]
    
    tsv_dump(tsv, rows, fields)

# %% ../nbs/01_tsv.ipynb #j4sm240mzn
def tsv_complete(
    tsv: str,                                       # TSV file path
    tasks: list[str] = ["translate", "mp3", "img"], # Tasks to run
    dirs: list[str] = ["audio", "images"],           # Directories for media
    model: str | None = None                        # Piper TTS model path (auto-downloaded if None)
) -> dict:
    """Run pipeline tasks on TSV (translate → mp3 → img).
    
    Each task is optional and runs only if listed in tasks.
    Results from each task are collected and returned.
    
    Args:
        tsv: TSV file path
        tasks: List of tasks to run. Options: "translate", "mp3", "img"
        dirs: Directories for media search (used by img task)
        model: Piper TTS model path for mp3 generation (auto-downloaded if None)
        
    Returns:
        Dict with results keyed by task name.
        Example: {"translate": {"translated": 2, ...}, "mp3": "done", "img": "done"}
    """
    result = {}
    
    if "translate" in tasks:
        result["translate"] = tsv_xlate(tsv)
    
    if "mp3" in tasks:
        tsv_mp3(tsv, model=model)
        result["mp3"] = "done"
    
    if "img" in tasks:
        tsv_img(tsv, dirs=dirs)
        result["img"] = "done"
    
    return result
