"""End-to-end workflow: Finnish texts → Translation → Audio → Anki cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_workflow.ipynb.

# %% auto 0
__all__ = ['create_cards']

# %% ../nbs/04_workflow.ipynb 2
from pathlib import Path

from .core import *
from .tsv import *
from .mp3 import *
from .anki import *

# %% ../nbs/04_workflow.ipynb 4
def create_cards(
    texts: list[str],
    deck: str,
    tags: str | list[str] = "lang::fi",
    output_dir: str = "output",
    overwrite: bool = False,
) -> Path:
    """
    Create Anki cards from Finnish texts (end-to-end workflow).
    
    Steps:
    1. Translate Finnish → English/Japanese (OpenAI API)
    2. Generate audio files (Piper TTS)
    3. Update TSV with file paths
    4. Upload to Anki (AnkiConnect)
    
    Args:
        texts: List of Finnish words/phrases to create cards for
        deck: Anki deck name (e.g., "06::Daily")
        tags: Tags for the cards (string or list), hierarchical format supported
              Examples: "src::daily", "src::class,level::A1", ["src::medical", "urgent"]
              Note: "lang::fi" is always auto-included
        output_dir: Directory for TSV and audio files (default: "output")
        overwrite: If True, delete existing deck and overwrite TSV file
    
    Example:
        >>> create_cards(
        ...     texts=["kissa", "koira"],
        ...     deck="06::Daily",
        ...     tags="src::daily"
        ... )
    """
    
    tsv_path = f"{output_dir}/{Path(deck.replace("::", "_")).stem + ".tsv"}"
    if overwrite:
        if deck in deckNames():
            deleteDeck(deck)
        # TSV will be auto-overwritten by texts2tsv()
    else:
        if Path(tsv_path).exists():
            raise FileExistsError(
                f"TSV file already exists: {tsv_path}\n"
                f"Use overwrite=True to replace it."
            )
        if deck in deckNames():
            raise ValueError(
                f"Deck '{deck}' already exists in Anki.\n"
                f"Use overwrite=True to replace it."
            )
        
    audio_dir = f"{output_dir}/audio"
    images_dir = f"{output_dir}/images"
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    texts2tsv(texts, tsv_path, tags=tags)
    mp3s(tsv_path, output_dir=audio_dir)
    update_tsv_media_paths(tsv_path, dirs=[audio_dir, images_dir])
    addnotes(deck, tsv_path)
    return tsv_path
