"""End-to-end workflow: Finnish texts → Translation → Audio → Anki cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_workflow.ipynb.

# %% auto #0
__all__ = ['register_cards', 'register_card']

# %% ../nbs/04_workflow.ipynb #20b24238
from pathlib import Path

from .core import *
from .tsv import *
from .mp3 import *
from .anki import *

# %% ../nbs/04_workflow.ipynb #bc2444b3
def register_cards(
    texts: list[str],
    deck: str,
    tags: str | list[str] = "lang::fi",
    output_dir: str = "output",
    overwrite: bool = False,
) -> str:
    """Create Anki cards from Finnish texts (end-to-end workflow).
    
    Steps:
    1. Create TSV with Finnish column (tsv_finnish)
    2. Fill translations + MP3 + images (tsv_complete)
    3. Upload to Anki (addnotes)
    
    Args:
        texts: Finnish words/phrases
        deck: Anki deck name (e.g., "06::Daily")
        tags: Tags for the cards
        output_dir: Directory for TSV and audio files
        overwrite: If True, overwrite existing TSV
    
    Returns:
        Path to created TSV file
    """
    tsv_path = f"{output_dir}/{Path(deck.replace('::', '_')).stem}.tsv"
    audio_dir = f"{output_dir}/audio"
    images_dir = f"{output_dir}/images"
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    tsv_finnish(texts, tsv_path, tags=tags, overwrite=overwrite)
    tsv_complete(tsv_path, dirs=[audio_dir, images_dir])
    addnotes(deck, tsv_path)
    
    return tsv_path

#| export
def register_card(
    text: str,
    deck: str,
    tags: str | list[str] = "lang::fi",
    output_dir: str = "output",
    overwrite: bool = False,
) -> str:
    """Register a single Finnish card to Anki.
    
    Convenience wrapper around register_cards() for single items.
    """
    return register_cards([text], deck, tags, output_dir, overwrite)
