"""End-to-end workflow: Finnish texts → Translation → Audio → Anki cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_workflow.ipynb.

# %% auto #0
__all__ = ['register_cards', 'register_txt', 'register_card', 'register_slice', 'register_latest', 'register_last']

# %% ../nbs/04_workflow.ipynb #20b24238
from pathlib import Path
import glob

from .core import *
from .tsv import *
from .mp3 import *
from .anki import *

# %% ../nbs/04_workflow.ipynb #bc2444b3
def register_cards(
    texts: list[str],
    deck: str,
    tags: str | list[str] = "lang::fi",
    output_dir: str = "output",
    overwrite: bool = False,
) -> str:
    """Create Anki cards from Finnish texts (end-to-end workflow).
    
    Steps:
    1. Create TSV with Finnish column (tsv_finnish)
    2. Fill translations + MP3 + images (tsv_complete)
    3. Upload to Anki (addnotes)
    
    Args:
        texts: Finnish words/phrases
        deck: Anki deck name (e.g., "06::Daily")
        tags: Tags for the cards
        output_dir: Directory for TSV and audio files
        overwrite: If True, overwrite existing TSV
    
    Returns:
        Path to created TSV file
    """
    tsv_path = f"{output_dir}/{Path(deck.replace('::', '_')).stem}.tsv"
    audio_dir = f"{output_dir}/audio"
    images_dir = f"{output_dir}/images"
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    print(deck, tsv_path)

    tsv_finnish(texts, tsv_path, tags=tags, overwrite=overwrite)
    tsv_complete(tsv_path, dirs=[audio_dir, images_dir])
    if overwrite: deleteDeck(deck)
    addnotes(deck, tsv_path)
    
    return tsv_path


def register_txt(
    txt: str,
    output_dir: str = "output",
    overwrite: bool = False,
) -> str:
    texts = cattxt(txt)
    stm = Path(txt).stem
    deck, tags = stm, [stm, stm.split('::')[-1]]
    return register_cards(texts, deck, tags, output_dir, overwrite)

def register_card(
    text: str,
    deck: str,
    tags: str | list[str] = "lang::fi",
    output_dir: str = "output",
    overwrite: bool = False,
) -> str:
    """Register a single Finnish card to Anki.
    
    Convenience wrapper around register_cards() for single items.
    """
    return register_cards([text], deck, tags, output_dir, overwrite)

# %% ../nbs/04_workflow.ipynb #a45d92b3-81c6-4c0a-82fd-ba527257d3cb
def register_slice(n:int, input_dir:str='texts', output_dir:str='output', overwrite:bool=False)->list[str]:
    fn = glob.glob(f"{input_dir}/*.txt")
    fn = sorted(fn, key=lambda f: Path(f).stat().st_mtime)
    fn = fn[:n] if n > 0 else fn[n:]
    return [register_txt(o, output_dir, overwrite) for o in fn]

def register_latest(input_dir:str='texts', output_dir:str="output", overwrite:bool=False)->str:
    return register_slice(-1, input_dir, output_dir, overwrite)[0]
def register_last(n:int, input_dir:str='texts', output_dir:str="output", overwrite:bool=False)->list[str]:
    return register_slice(-n, input_dir, output_dir, overwrite)
